react rule 에 jsx-key 추가
channel-io/eslint-config pull request #27
Opened 2021-11-30 11:12 UTC by npbg

JSX 문에서 map() 등의 iterate 메소드를 써서 컴포넌트를 렌더할 때 key prop 을 놓치지 않게 하는
**react/jsx-key** rule 을 **error** 레벨로 추가했습니다.

2021-11-30 11:14 UTC, sungik-choi approved these changes
너무 좋네요

2021-11-30 13:53 UTC, Seolhun commented
필요하긴 합니다만, 이것만 넣으면 현재 동작되던 빌드 프로세스에서 에러발생은 안되나요?

2021-11-30 13:58 UTC, Seolhun commented
warning에서 정해진 기간 이후로 error로 가면 좋을것 같긴합니다.

2021-12-01 05:14 UTC, Seolhun approved these changes

2021-12-01 06:22 UTC, Junbong requested changes

2021-12-01 06:22 UTC, Junbong commented on rules/react.js
> +  'react/jsx-key': 'warn', // Checks required key prop in JSX exist
주기적으로 TODO 검색하고 있고 또 IDE에서 알람을 받을 수도 있어서요,
주석을 TODO로 달아주시면 더 놓치지 않을 수 있을 것 같습니다.

```suggestion
  'react/jsx-key': 'warn',  // TODO (@axel): Checks required key prop in JSX exist
```

2021-12-02 02:57 UTC, aooen approved these changes

2021-12-03 00:09 UTC, npbg commented on rules/react.js
> +  'react/jsx-key': 'warn', // Checks required key prop in JSX exist
반영했습니다!

2021-12-03 02:50 UTC, quino0627 approved these changes

2021-12-03 03:14 UTC, Junbong approved these changes

2021-12-03 03:14 UTC, merged